# Generated by Django 5.2.7 on 2026-02-23 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesession',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
