# Generated by Django 5.2.7 on 2026-03-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesession_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('company', 'Head Office'), ('warehouse', 'Warehouse Manager'), ('branch', 'Branch Manager'), ('teller', 'Teller (Returns Staff)'), ('guard', 'Security Guard')], default='company', max_length=20),
        ),
    ]
